import { APP_ROUTES } from "@/constants/routes";

export const PERMISSIONS = {
  ADMIN_DASHBOARD_MAIN: "view_admin_dashboard",
  ADMIN_ROLES_READ: "read_admin_roles",
  ADMIN_ROLES_CREATE: "create_admin_roles",
  ADMIN_ROLES_UPDATE: "update_admin_roles",
  ADMIN_ROLES_DELETE: "delete_admin_roles",
  ADMIN_PERMISSIONS_READ: "read_admin_permissions",
  ADMIN_PERMISSIONS_CREATE: "create_admin_permissions",
  ADMIN_PERMISSIONS_UPDATE: "update_admin_permissions",
  ADMIN_PERMISSIONS_DELETE: "delete_admin_permissions",
  ADMIN_USERS_READ: "read_admin_users",
  ADMIN_USERS_CREATE: "create_admin_users",
  ADMIN_USERS_UPDATE: "update_admin_users",
  ADMIN_USERS_DELETE: "delete_admin_users",
  ADMIN_FAQS_READ: "read_admin_faqs",
  ADMIN_FAQS_CREATE: "create_admin_faqs",
  ADMIN_FAQS_UPDATE: "update_admin_faqs",
  ADMIN_FAQS_DELETE: "delete_admin_faqs",
  ADMIN_CONTACTS_READ: "read_admin_contacts",
  ADMIN_CONTACTS_UPDATE: "update_admin_contacts",
  ADMIN_CONTACTS_DELETE: "delete_admin_contacts",
  ADMIN_API_CLIENTS_READ: "read_admin_api_clients",
  ADMIN_API_CLIENTS_CREATE: "create_admin_api_clients",
  ADMIN_API_CLIENTS_UPDATE: "update_admin_api_clients",
  ADMIN_API_CLIENTS_DELETE: "delete_admin_api_clients",
  ADMIN_SIDE_PAGE_VIEWS_READ: "read_admin_side_page_views",
  ADMIN_TUTORIAL_PLAYLISTS_READ: "read_admin_tutorial_playlists",
  ADMIN_TUTORIAL_PLAYLISTS_CREATE: "create_admin_tutorial_playlists",
  ADMIN_TUTORIAL_PLAYLISTS_UPDATE: "update_admin_tutorial_playlists",
  ADMIN_TUTORIAL_PLAYLISTS_DELETE: "delete_admin_tutorial_playlists",
  ADMIN_CACHES_READ: "read_admin_caches",
  ADMIN_CACHES_UPDATE: "update_admin_caches",
  ADMIN_CACHES_DELETE: "delete_admin_caches",
  ADMIN_AUTHENTICATION_LOGS_READ: "read_admin_authentication_logs",
  ADMIN_AUTHENTICATION_LOGS_UPDATE: "update_admin_authentication_logs",
  ADMIN_AUTHENTICATION_LOGS_DELETE: "delete_admin_authentication_logs",
  ADMIN_KINERJA_EKONOMI_READ: "read_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_CURRENT_READ: "read_admin_kinerja_ekonomi_current",
  ADMIN_KINERJA_EKONOMI_CURRENT_UPDATE: "update_admin_kinerja_ekonomi_current",
  ADMIN_KINERJA_EKONOMI_CURRENT_DELETE: "delete_admin_kinerja_ekonomi_current",
  ADMIN_KINERJA_EKONOMI_READ_ALL: "read_all_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_CREATE: "create_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_UPDATE: "update_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_APPROVE: "approve_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_PUBLISH: "publish_admin_kinerja_ekonomi",
  ADMIN_KINERJA_EKONOMI_DELETE: "delete_admin_kinerja_ekonomi",
  ADMIN_TRADE_READ: "read_admin_perdagangan",
  ADMIN_TRADE_CURRENT_READ: "read_admin_perdagangan_current",
  ADMIN_TRADE_CURRENT_UPDATE: "update_admin_perdagangan_current",
  ADMIN_TRADE_CURRENT_DELETE: "delete_admin_perdagangan_current",
  ADMIN_TRADE_READ_ALL: "read_all_admin_perdagangan",
  ADMIN_TRADE_CREATE: "create_admin_perdagangan",
  ADMIN_TRADE_UPDATE: "update_admin_perdagangan",
  ADMIN_TRADE_APPROVE: "approve_admin_perdagangan",
  ADMIN_TRADE_PUBLISH: "publish_admin_perdagangan",
  ADMIN_TRADE_DELETE: "delete_admin_perdagangan",
  ADMIN_INVESTMENT_READ: "read_admin_investasi",
  ADMIN_INVESTMENT_CURRENT_READ: "read_admin_investasi_current",
  ADMIN_INVESTMENT_CURRENT_UPDATE: "update_admin_investasi_current",
  ADMIN_INVESTMENT_CURRENT_DELETE: "delete_admin_investasi_current",
  ADMIN_INVESTMENT_READ_ALL: "read_all_admin_investasi",
  ADMIN_INVESTMENT_CREATE: "create_admin_investasi",
  ADMIN_INVESTMENT_UPDATE: "update_admin_investasi",
  ADMIN_INVESTMENT_APPROVE: "approve_admin_investasi",
  ADMIN_INVESTMENT_PUBLISH: "publish_admin_investasi",
  ADMIN_INVESTMENT_DELETE: "delete_admin_investasi",
  ADMIN_TOURISM_READ: "read_admin_pariwisata",
  ADMIN_TOURISM_CURRENT_READ: "read_admin_pariwisata_current",
  ADMIN_TOURISM_CURRENT_UPDATE: "update_admin_pariwisata_current",
  ADMIN_TOURISM_CURRENT_DELETE: "delete_admin_pariwisata_current",
  ADMIN_TOURISM_READ_ALL: "read_all_admin_pariwisata",
  ADMIN_TOURISM_CREATE: "create_admin_pariwisata",
  ADMIN_TOURISM_UPDATE: "update_admin_pariwisata",
  ADMIN_TOURISM_APPROVE: "approve_admin_pariwisata",
  ADMIN_TOURISM_PUBLISH: "publish_admin_pariwisata",
  ADMIN_TOURISM_DELETE: "delete_admin_pariwisata",
  INDONESIA_DIPLOMASI_EKONOMI: "view_diplomasi_ekonomi_indonesia",
  INDONESIA_KERJASAMA_BILATERAL: "view_kerjasama_bilateral_indonesia",
  INDONESIA_KINERJA_EKONOMI: "view_kinerja_ekonomi_indonesia",
  INDONESIA_INFRASTRUKTUR: "view_infrastruktur_indonesia",
  MITRA_OVERVIEW: "view_overview_negara_mitra",
  MITRA_PERDAGANGAN: "view_perdagangan_negara_mitra",
  MITRA_INVESTASI: "view_investasi_negara_mitra",
  MITRA_PARIWISATA: "view_pariwisata_negara_mitra",
  MITRA_JASA: "view_jasa_negara_mitra",
  SEKTOR_ARUS_TIK_PRIORITAS: "view_arus_tik_prioritas",
  SEKTOR_ENERGI_PRIORITAS: "view_energi_prioritas",
  SEKTOR_MINERAL_KRITIS_PRIORITAS: "view_mineral_kritis_prioritas",
  SEKTOR_FARMASI_PRIORITAS: "view_farmasi_prioritas",
  SEKTOR_HILIRISASI_PRIORITAS: "view_hilirisasi_prioritas",
  SEKTOR_PANGAN_PRIORITAS: "view_pangan_prioritas",
  SEKTOR_PERTAHANAN_PRIORITAS: "view_pertahanan_prioritas",
  SEKTOR_PERDAGANGAN: "view_sektor_perdagangan",
  SEKTOR_INVESTASI: "view_sektor_investasi",
  SEKTOR_PAREKRAF: "view_sektor_parekraf",
  SEKTOR_PETA_PERSEBARAN_WISMAN: "view_peta_persebaran_wisman",
  SEKTOR_PETA_PERJALANAN_TRANSPORTASI: "view_peta_perjalanan_transportasi",
  SEKTOR_DAYA_SAING_PARIWISATA_PROVINSI:
    "view_analisis_daya_saing_pariwisata_provinsi",
  SEKTOR_INDEKS_DAYA_SAING_PARIWISATA_NEGARA:
    "view_indeks_daya_saing_pariwisata_negara",
  SEKTOR_SEGMENTASI_FREKUENSI_MONETER: "view_segmentasi_frekuensi_moneter",
  SEKTOR_JASA: "view_sektor_jasa",
  SEKTOR_DATA_PEKERJA_MIGRAN: "view_data_pekerja_migran_indonesia",
  SEKTOR_INSIGHT_PASAR_JASA: "view_insight_pasar_jasa",
  SEKTOR_KSPI: "view_sektor_kspi",
  ANALISIS_PRODUK_KOMODITAS: "view_produk_komoditas_analisis",
  ANALISIS_POTENSI_DAYA_SAING: "view_potensi_daya_saing_analisis",
  ANALISIS_IDE: "view_ide_analisis",
  ANALISIS_OPERATIONAL_RISK: "view_operational_risk_analisis",
  ANALISIS_GEOPOLITIK_PERDAGANGAN: "view_geopolitik_perdagangan_analisis",
  DATABANK_PERDAGANGAN_DATA_GENERATOR: "view_perdagangan_data_generator",
  DATABANK_TURIS_DATA_GENERATOR: "view_turis_data_generator",
  DATABANK_INVESTASI_DATA_GENERATOR: "view_investasi_data_generator",
  DATABANK_JASA_DATA_GENERATOR: "view_jasa_data_generator",
  DATABANK_INDIKATOR_EKONOMI_DATA_GENERATOR:
    "view_indikator_ekonomi_data_generator",
  DATABANK_RCA_CMSA_REPORT_GENERATOR: "view_rca_cmsa_report_generator",
  DATABANK_MARKET_SHARE_REPORT_GENERATOR: "view_market_share_report_generator",
  DATABANK_KERJASAMA_PERDAGANGAN_REPORT_GENERATOR:
    "view_kerjasama_perdagangan_report_generator"
} as const;

export type AppPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type PermissionPathMap = Partial<Record<AppPermission, string>>;

export const PERMISSION_GROUPS = {
  ADMIN_DASHBOARD: [
    PERMISSIONS.ADMIN_DASHBOARD_MAIN,
    PERMISSIONS.ADMIN_ROLES_READ,
    PERMISSIONS.ADMIN_ROLES_CREATE,
    PERMISSIONS.ADMIN_ROLES_UPDATE,
    PERMISSIONS.ADMIN_ROLES_DELETE,
    PERMISSIONS.ADMIN_PERMISSIONS_READ,
    PERMISSIONS.ADMIN_PERMISSIONS_CREATE,
    PERMISSIONS.ADMIN_PERMISSIONS_UPDATE,
    PERMISSIONS.ADMIN_PERMISSIONS_DELETE,
    PERMISSIONS.ADMIN_USERS_READ,
    PERMISSIONS.ADMIN_USERS_CREATE,
    PERMISSIONS.ADMIN_USERS_UPDATE,
    PERMISSIONS.ADMIN_USERS_DELETE,
    PERMISSIONS.ADMIN_FAQS_READ,
    PERMISSIONS.ADMIN_FAQS_CREATE,
    PERMISSIONS.ADMIN_FAQS_UPDATE,
    PERMISSIONS.ADMIN_FAQS_DELETE,
    PERMISSIONS.ADMIN_CONTACTS_READ,
    PERMISSIONS.ADMIN_CONTACTS_UPDATE,
    PERMISSIONS.ADMIN_CONTACTS_DELETE,
    PERMISSIONS.ADMIN_API_CLIENTS_READ,
    PERMISSIONS.ADMIN_API_CLIENTS_CREATE,
    PERMISSIONS.ADMIN_API_CLIENTS_UPDATE,
    PERMISSIONS.ADMIN_API_CLIENTS_DELETE,
    PERMISSIONS.ADMIN_SIDE_PAGE_VIEWS_READ,
    PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_READ,
    PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_CREATE,
    PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_UPDATE,
    PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_DELETE,
    PERMISSIONS.ADMIN_CACHES_READ,
    PERMISSIONS.ADMIN_CACHES_UPDATE,
    PERMISSIONS.ADMIN_CACHES_DELETE,
    PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_READ,
    PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_UPDATE,
    PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_DELETE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_READ,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_READ,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_UPDATE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_DELETE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_READ_ALL,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_CREATE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_UPDATE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_APPROVE,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_PUBLISH,
    PERMISSIONS.ADMIN_KINERJA_EKONOMI_DELETE,
    PERMISSIONS.ADMIN_TRADE_READ,
    PERMISSIONS.ADMIN_TRADE_CURRENT_READ,
    PERMISSIONS.ADMIN_TRADE_CURRENT_UPDATE,
    PERMISSIONS.ADMIN_TRADE_CURRENT_DELETE,
    PERMISSIONS.ADMIN_TRADE_READ_ALL,
    PERMISSIONS.ADMIN_TRADE_CREATE,
    PERMISSIONS.ADMIN_TRADE_UPDATE,
    PERMISSIONS.ADMIN_TRADE_APPROVE,
    PERMISSIONS.ADMIN_TRADE_PUBLISH,
    PERMISSIONS.ADMIN_TRADE_DELETE,
    PERMISSIONS.ADMIN_INVESTMENT_READ,
    PERMISSIONS.ADMIN_INVESTMENT_CURRENT_READ,
    PERMISSIONS.ADMIN_INVESTMENT_CURRENT_UPDATE,
    PERMISSIONS.ADMIN_INVESTMENT_CURRENT_DELETE,
    PERMISSIONS.ADMIN_INVESTMENT_READ_ALL,
    PERMISSIONS.ADMIN_INVESTMENT_CREATE,
    PERMISSIONS.ADMIN_INVESTMENT_UPDATE,
    PERMISSIONS.ADMIN_INVESTMENT_APPROVE,
    PERMISSIONS.ADMIN_INVESTMENT_PUBLISH,
    PERMISSIONS.ADMIN_INVESTMENT_DELETE,
    PERMISSIONS.ADMIN_TOURISM_READ,
    PERMISSIONS.ADMIN_TOURISM_CURRENT_READ,
    PERMISSIONS.ADMIN_TOURISM_CURRENT_UPDATE,
    PERMISSIONS.ADMIN_TOURISM_CURRENT_DELETE,
    PERMISSIONS.ADMIN_TOURISM_READ_ALL,
    PERMISSIONS.ADMIN_TOURISM_CREATE,
    PERMISSIONS.ADMIN_TOURISM_UPDATE,
    PERMISSIONS.ADMIN_TOURISM_APPROVE,
    PERMISSIONS.ADMIN_TOURISM_PUBLISH,
    PERMISSIONS.ADMIN_TOURISM_DELETE
  ],
  INDONESIA: [
    PERMISSIONS.INDONESIA_DIPLOMASI_EKONOMI,
    PERMISSIONS.INDONESIA_KERJASAMA_BILATERAL,
    PERMISSIONS.INDONESIA_KINERJA_EKONOMI,
    PERMISSIONS.INDONESIA_INFRASTRUKTUR
  ],
  MITRA: [
    PERMISSIONS.MITRA_OVERVIEW,
    PERMISSIONS.MITRA_PERDAGANGAN,
    PERMISSIONS.MITRA_INVESTASI,
    PERMISSIONS.MITRA_PARIWISATA,
    PERMISSIONS.MITRA_JASA
  ],
  SEKTOR_KOMODITAS_UTAMA: [
    PERMISSIONS.SEKTOR_ARUS_TIK_PRIORITAS,
    PERMISSIONS.SEKTOR_ENERGI_PRIORITAS,
    PERMISSIONS.SEKTOR_MINERAL_KRITIS_PRIORITAS,
    PERMISSIONS.SEKTOR_FARMASI_PRIORITAS,
    PERMISSIONS.SEKTOR_HILIRISASI_PRIORITAS,
    PERMISSIONS.SEKTOR_PANGAN_PRIORITAS,
    PERMISSIONS.SEKTOR_PERTAHANAN_PRIORITAS
  ],
  SEKTOR_PERDAGANGAN: [PERMISSIONS.SEKTOR_PERDAGANGAN],
  SEKTOR_INVESTASI: [PERMISSIONS.SEKTOR_INVESTASI],
  SEKTOR_PAREKRAF: [
    PERMISSIONS.SEKTOR_PAREKRAF,
    PERMISSIONS.SEKTOR_PETA_PERSEBARAN_WISMAN,
    PERMISSIONS.SEKTOR_PETA_PERJALANAN_TRANSPORTASI,
    PERMISSIONS.SEKTOR_DAYA_SAING_PARIWISATA_PROVINSI,
    PERMISSIONS.SEKTOR_INDEKS_DAYA_SAING_PARIWISATA_NEGARA,
    PERMISSIONS.SEKTOR_SEGMENTASI_FREKUENSI_MONETER
  ],
  SEKTOR_JASA: [
    PERMISSIONS.SEKTOR_JASA,
    PERMISSIONS.SEKTOR_DATA_PEKERJA_MIGRAN,
    PERMISSIONS.SEKTOR_INSIGHT_PASAR_JASA
  ],
  SEKTOR_KSPI: [PERMISSIONS.SEKTOR_KSPI],
  ANALISIS: [
    PERMISSIONS.ANALISIS_PRODUK_KOMODITAS,
    PERMISSIONS.ANALISIS_POTENSI_DAYA_SAING,
    PERMISSIONS.ANALISIS_IDE,
    PERMISSIONS.ANALISIS_OPERATIONAL_RISK,
    PERMISSIONS.ANALISIS_GEOPOLITIK_PERDAGANGAN
  ],
  DATABANK: [
    PERMISSIONS.DATABANK_PERDAGANGAN_DATA_GENERATOR,
    PERMISSIONS.DATABANK_TURIS_DATA_GENERATOR,
    PERMISSIONS.DATABANK_INVESTASI_DATA_GENERATOR,
    PERMISSIONS.DATABANK_JASA_DATA_GENERATOR,
    PERMISSIONS.DATABANK_INDIKATOR_EKONOMI_DATA_GENERATOR,
    PERMISSIONS.DATABANK_RCA_CMSA_REPORT_GENERATOR,
    PERMISSIONS.DATABANK_MARKET_SHARE_REPORT_GENERATOR,
    PERMISSIONS.DATABANK_KERJASAMA_PERDAGANGAN_REPORT_GENERATOR
  ],
  DATABANK_DATA_GENERATOR: [
    PERMISSIONS.DATABANK_PERDAGANGAN_DATA_GENERATOR,
    PERMISSIONS.DATABANK_TURIS_DATA_GENERATOR,
    PERMISSIONS.DATABANK_INVESTASI_DATA_GENERATOR,
    PERMISSIONS.DATABANK_JASA_DATA_GENERATOR,
    PERMISSIONS.DATABANK_INDIKATOR_EKONOMI_DATA_GENERATOR
  ],
  DATABANK_REPORT_GENERATOR: [
    PERMISSIONS.DATABANK_RCA_CMSA_REPORT_GENERATOR,
    PERMISSIONS.DATABANK_MARKET_SHARE_REPORT_GENERATOR,
    PERMISSIONS.DATABANK_KERJASAMA_PERDAGANGAN_REPORT_GENERATOR
  ]
} as const;

export const PERMISSION_ROUTES = {
  ADMIN_DASHBOARD: {
    [PERMISSIONS.ADMIN_DASHBOARD_MAIN]: APP_ROUTES.ADMIN_MANAGEMENT.DASHBOARD,
    [PERMISSIONS.ADMIN_ROLES_READ]: APP_ROUTES.ADMIN_MANAGEMENT.ROLES,
    [PERMISSIONS.ADMIN_ROLES_CREATE]: APP_ROUTES.ADMIN_MANAGEMENT.ROLES,
    [PERMISSIONS.ADMIN_ROLES_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.ROLES,
    [PERMISSIONS.ADMIN_ROLES_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.ROLES,
    [PERMISSIONS.ADMIN_PERMISSIONS_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.PERMISSIONS,
    [PERMISSIONS.ADMIN_PERMISSIONS_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.PERMISSIONS,
    [PERMISSIONS.ADMIN_PERMISSIONS_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.PERMISSIONS,
    [PERMISSIONS.ADMIN_PERMISSIONS_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.PERMISSIONS,
    [PERMISSIONS.ADMIN_USERS_READ]: APP_ROUTES.ADMIN_MANAGEMENT.USERS,
    [PERMISSIONS.ADMIN_USERS_CREATE]: APP_ROUTES.ADMIN_MANAGEMENT.USERS,
    [PERMISSIONS.ADMIN_USERS_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.USERS,
    [PERMISSIONS.ADMIN_USERS_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.USERS,
    [PERMISSIONS.ADMIN_FAQS_READ]: APP_ROUTES.ADMIN_MANAGEMENT.FAQS,
    [PERMISSIONS.ADMIN_FAQS_CREATE]: APP_ROUTES.ADMIN_MANAGEMENT.FAQS,
    [PERMISSIONS.ADMIN_FAQS_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.FAQS,
    [PERMISSIONS.ADMIN_FAQS_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.FAQS,
    [PERMISSIONS.ADMIN_CONTACTS_READ]: APP_ROUTES.ADMIN_MANAGEMENT.CONTACTS,
    [PERMISSIONS.ADMIN_CONTACTS_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.CONTACTS,
    [PERMISSIONS.ADMIN_CONTACTS_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.CONTACTS,
    [PERMISSIONS.ADMIN_API_CLIENTS_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.API_CLIENTS,
    [PERMISSIONS.ADMIN_API_CLIENTS_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.API_CLIENTS,
    [PERMISSIONS.ADMIN_API_CLIENTS_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.API_CLIENTS,
    [PERMISSIONS.ADMIN_API_CLIENTS_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.API_CLIENTS,
    [PERMISSIONS.ADMIN_SIDE_PAGE_VIEWS_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.SIDE_PAGE_VIEWS,
    [PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.TUTORIAL_PLAYLISTS,
    [PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TUTORIAL_PLAYLISTS,
    [PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TUTORIAL_PLAYLISTS,
    [PERMISSIONS.ADMIN_TUTORIAL_PLAYLISTS_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TUTORIAL_PLAYLISTS,
    [PERMISSIONS.ADMIN_CACHES_READ]: APP_ROUTES.ADMIN_MANAGEMENT.CACHES,
    [PERMISSIONS.ADMIN_CACHES_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.CACHES,
    [PERMISSIONS.ADMIN_CACHES_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.CACHES,
    [PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.AUTHENTICATION_LOGS,
    [PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.AUTHENTICATION_LOGS,
    [PERMISSIONS.ADMIN_AUTHENTICATION_LOGS_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.AUTHENTICATION_LOGS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_CURRENT_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_READ_ALL]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_APPROVE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_PUBLISH]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_KINERJA_EKONOMI_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.ECONOMIC_INDICATORS,
    [PERMISSIONS.ADMIN_TRADE_READ]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_CURRENT_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_CURRENT_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_CURRENT_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_READ_ALL]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_CREATE]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_UPDATE]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_APPROVE]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_PUBLISH]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_TRADE_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.TRADE_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_CURRENT_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_CURRENT_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_CURRENT_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_READ_ALL]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_APPROVE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_PUBLISH]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_INVESTMENT_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.INVESTMENT_DATA,
    [PERMISSIONS.ADMIN_TOURISM_READ]: APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_CURRENT_READ]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_CURRENT_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_CURRENT_DELETE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_READ_ALL]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_CREATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_UPDATE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_APPROVE]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_PUBLISH]:
      APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA,
    [PERMISSIONS.ADMIN_TOURISM_DELETE]: APP_ROUTES.ADMIN_MANAGEMENT.TOURISM_DATA
  },
  INDONESIA: {
    [PERMISSIONS.INDONESIA_DIPLOMASI_EKONOMI]:
      APP_ROUTES.INDONESIA.DIPLOMASI_EKONOMI,
    [PERMISSIONS.INDONESIA_KERJASAMA_BILATERAL]:
      APP_ROUTES.INDONESIA.KERJASAMA_BILATERAL,
    [PERMISSIONS.INDONESIA_KINERJA_EKONOMI]:
      APP_ROUTES.INDONESIA.INDIKATOR_EKONOMI,
    [PERMISSIONS.INDONESIA_INFRASTRUKTUR]: APP_ROUTES.INDONESIA.INFRASTRUKTUR
  },
  MITRA: {
    [PERMISSIONS.MITRA_OVERVIEW]: APP_ROUTES.MITRA.OVERVIEW,
    [PERMISSIONS.MITRA_PERDAGANGAN]: APP_ROUTES.MITRA.PERDAGANGAN,
    [PERMISSIONS.MITRA_INVESTASI]: APP_ROUTES.MITRA.INVESTASI,
    [PERMISSIONS.MITRA_PARIWISATA]: APP_ROUTES.MITRA.PARIWISATA,
    [PERMISSIONS.MITRA_JASA]: APP_ROUTES.MITRA.JASA
  },
  ANALISIS: {
    [PERMISSIONS.ANALISIS_PRODUK_KOMODITAS]:
      APP_ROUTES.ANALISIS.PRODUK_KOMODITAS,
    [PERMISSIONS.ANALISIS_POTENSI_DAYA_SAING]:
      APP_ROUTES.ANALISIS.POTENSI_DAYA_SAING,
    [PERMISSIONS.ANALISIS_IDE]: APP_ROUTES.ANALISIS.IDE,
    [PERMISSIONS.ANALISIS_OPERATIONAL_RISK]:
      APP_ROUTES.ANALISIS.OPERATIONAL_RISK,
    [PERMISSIONS.ANALISIS_GEOPOLITIK_PERDAGANGAN]:
      APP_ROUTES.ANALISIS.GEOPOLITIK_PERDAGANGAN
  },
  DATABANK: {
    [PERMISSIONS.DATABANK_PERDAGANGAN_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.TRADE,
    [PERMISSIONS.DATABANK_TURIS_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.TOURISM,
    [PERMISSIONS.DATABANK_INVESTASI_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.INVESTMENT,
    [PERMISSIONS.DATABANK_JASA_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.SERVICE,
    [PERMISSIONS.DATABANK_INDIKATOR_EKONOMI_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.INDIKATOR_EKONOMI,
    [PERMISSIONS.DATABANK_RCA_CMSA_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.RCA_CMSA,
    [PERMISSIONS.DATABANK_MARKET_SHARE_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.MARKET_SHARE,
    [PERMISSIONS.DATABANK_KERJASAMA_PERDAGANGAN_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.KERJASAMA_PERDAGANGAN
  },
  DATABANK_DATA_GENERATOR: {
    [PERMISSIONS.DATABANK_PERDAGANGAN_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.TRADE,
    [PERMISSIONS.DATABANK_TURIS_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.TOURISM,
    [PERMISSIONS.DATABANK_INVESTASI_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.INVESTMENT,
    [PERMISSIONS.DATABANK_JASA_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.SERVICE,
    [PERMISSIONS.DATABANK_INDIKATOR_EKONOMI_DATA_GENERATOR]:
      APP_ROUTES.DATABANK.DATA_GENERATOR.INDIKATOR_EKONOMI
  },
  DATABANK_REPORT_GENERATOR: {
    [PERMISSIONS.DATABANK_RCA_CMSA_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.RCA_CMSA,
    [PERMISSIONS.DATABANK_MARKET_SHARE_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.MARKET_SHARE,
    [PERMISSIONS.DATABANK_KERJASAMA_PERDAGANGAN_REPORT_GENERATOR]:
      APP_ROUTES.DATABANK.REPORT_GENERATOR.KERJASAMA_PERDAGANGAN
  }
} as const satisfies Record<string, PermissionPathMap>;
